        <nav>
            <div>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="jobs.html">Jobs</a></li>
                    <li><a href="apply.html">Apply</a></li>
                    <li><a href="about.html">About</a></li>
                </ul>
            </div>
            <div>
                <h1><?php echo $pageTitle; ?></h1>
            </div>
        </nav>